AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ValuesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 5
      Role: 'arn:aws:iam::957887051703:role/LambdaRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /names
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /feature
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /attribute
            Method: ANY
